from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse
from app.core.logger import app_logger
from app.schemas.report import GenerateReportRequest
from app.services.storage_service import get_storage_service, StorageService
from app.services.llm_service import get_llm_service, LLMService

router = APIRouter()


@router.get("/")
async def list_reports(storage: StorageService = Depends(get_storage_service)):
    """Lists all archived AI-generated incident reports."""
    app_logger.info("Fetching all incident reports")
    return storage.get_all_reports()


@router.get("/{report_id}/download", response_class=HTMLResponse)
async def download_report(report_id: str, storage: StorageService = Depends(get_storage_service)):
    """
    Gap 3 — Downloadable Incident Report

    Returns the incident report as a self-contained HTML document that the
    browser prompts the user to download (Content-Disposition: attachment).
    Uses the `markdown` package to convert the stored markdown to HTML.
    """
    app_logger.info(f"Download request for report ID: {report_id}")
    report = storage.get_report_by_id(report_id)
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    markdown_content: str = report.get("report_markdown", "# No content available")
    severity_label: str = report.get("severity_label", "UNKNOWN")
    source_ip: str = report.get("source_ip", "Unknown")
    ts: str = report.get("timestamp", "")

    # Convert markdown → HTML
    try:
        import markdown as md_lib
        body_html = md_lib.markdown(markdown_content, extensions=["extra", "nl2br"])
    except Exception:
        # Graceful fallback: wrap plain text
        body_html = f"<pre>{markdown_content}</pre>"

    severity_color = {
        "CRITICAL": "#dc2626",
        "HIGH":     "#ea580c",
        "MEDIUM":   "#ca8a04",
        "LOW":      "#16a34a",
    }.get(severity_label.upper(), "#6b7280")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Incident Report — {report_id}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #0f172a;
      color: #e2e8f0;
      padding: 2rem;
      line-height: 1.7;
    }}
    .report-header {{
      border-left: 4px solid {severity_color};
      padding: 1rem 1.5rem;
      background: #1e293b;
      border-radius: 0 8px 8px 0;
      margin-bottom: 2rem;
    }}
    .report-header h1 {{
      font-size: 1.5rem;
      color: #f1f5f9;
      margin-bottom: 0.5rem;
    }}
    .meta {{ display: flex; gap: 1.5rem; flex-wrap: wrap; }}
    .meta span {{
      font-size: 0.85rem;
      background: #334155;
      padding: 0.25rem 0.75rem;
      border-radius: 999px;
      color: #94a3b8;
    }}
    .severity-badge {{
      background: {severity_color}22;
      color: {severity_color};
      border: 1px solid {severity_color}55;
      font-weight: 700;
    }}
    .report-body {{
      background: #1e293b;
      border-radius: 8px;
      padding: 2rem;
      max-width: 860px;
      margin: 0 auto;
    }}
    h1, h2, h3 {{ color: #f1f5f9; margin: 1.25rem 0 0.5rem; }}
    h2 {{ border-bottom: 1px solid #334155; padding-bottom: 0.4rem; }}
    p {{ margin-bottom: 0.75rem; color: #cbd5e1; }}
    code {{ background: #0f172a; color: #7dd3fc; padding: 0.1rem 0.4rem; border-radius: 4px; font-size: 0.9em; }}
    pre {{ background: #0f172a; color: #7dd3fc; padding: 1rem; border-radius: 6px; overflow-x: auto; margin: 1rem 0; }}
    ul, ol {{ margin: 0.5rem 0 0.75rem 1.5rem; color: #cbd5e1; }}
    li {{ margin-bottom: 0.3rem; }}
    strong {{ color: #f8fafc; }}
    blockquote {{ border-left: 3px solid #475569; padding-left: 1rem; color: #94a3b8; margin: 0.5rem 0; }}
    hr {{ border: none; border-top: 1px solid #334155; margin: 1.5rem 0; }}
    .footer {{
      text-align: center;
      margin-top: 2rem;
      color: #475569;
      font-size: 0.8rem;
    }}
  </style>
</head>
<body>
  <div class="report-body">
    <div class="report-header">
      <h1>🔍 Incident Report</h1>
      <div class="meta">
        <span>ID: {report_id}</span>
        <span>Source IP: {source_ip}</span>
        <span>Timestamp: {ts}</span>
        <span class="severity-badge">⚠ {severity_label}</span>
      </div>
    </div>
    {body_html}
    <div class="footer">
      <p>Generated by The Noir — AI-Powered SOC Automation Platform</p>
      <p>Report ID: {report_id}</p>
    </div>
  </div>
</body>
</html>"""

    return HTMLResponse(
        content=html,
        headers={
            "Content-Disposition": f'attachment; filename="incident-report-{report_id}.html"'
        }
    )


@router.get("/{report_id}")
async def get_report(report_id: str, storage: StorageService = Depends(get_storage_service)):
    """Retrieves a specific incident report by ID."""
    app_logger.info(f"Fetching report ID: {report_id}")
    report = storage.get_report_by_id(report_id)
    if not report:
        app_logger.warning(f"Report ID not found: {report_id}")
        raise HTTPException(status_code=404, detail="Report not found")
    return report


@router.post("/generate")
async def generate_new_report(
    request: GenerateReportRequest,
    llm: LLMService = Depends(get_llm_service),
    storage: StorageService = Depends(get_storage_service)
):
    """Triggers LLM analyst to generate and save a new report."""
    app_logger.info(f"Initiating AI forensic report generation for IP: {request.log_data.get('ip_address')}")

    # 1. Calculate Severity
    severity = llm.calculate_severity(request.ml_result, request.log_data)
    app_logger.debug(f"Calculated severity: {severity['label']} ({severity['score']})")

    # 2. Generate Report
    markdown_content = await llm.generate_incident_report(request.log_data, request.ml_result, severity)
    app_logger.debug("Markdown string generation complete")

    # 3. Store Report
    report_id = storage.save_incident_report(request.log_data, request.ml_result, severity, markdown_content)
    app_logger.info(f"Report successfully generated and stored. ID: {report_id}")

    return {
        "report_id": report_id,
        "severity": severity,
        "markdown": markdown_content
    }
